// ============================================================
// 🔒 BLOC-DATA — data.js [VERROUILLÉ]
// Contient : CM (catégories), RES_SECTIONS, RES_DEFAULT, DATA
// ⚠️ Ne pas modifier sans accord explicite
// ============================================================

// ── Catégories ──
const CM = {
  salutations:  { l: 'Salutations',        bg: '#E2F5EF', c: '#2D6B4A' },
  politesse:    { l: 'Politesse',           bg: '#E8F8F0', c: '#1A5C3A' },
  questions:    { l: 'Questions',           bg: '#FAF0E8', c: '#7A3B1A' },
  compliments:  { l: 'Compliments',         bg: '#FDF4E0', c: '#7A5C1A' },
  humour:       { l: 'Humour',              bg: '#F6ECF8', c: '#6B2D72' },
  famille:      { l: 'Famille',             bg: '#FFF0F0', c: '#8C2020' },
  maison:       { l: 'Maison & Repas',      bg: '#FFF6E8', c: '#7A4A10' },
  ville:        { l: 'Ville & Déplacements',bg: '#EAF4FF', c: '#1A4A7A' },
  chiffres:     { l: 'Chiffres & Temps',    bg: '#F0F8EE', c: '#2A5C20' },
  fruits:       { l: 'Fruits & Légumes',    bg: '#F5FAEC', c: '#3A6010' },
  religion:     { l: 'Religion & Fêtes',    bg: '#FDF8EE', c: '#7A5E10' },
  emotions:     { l: 'Émotions',            bg: '#FDF0F8', c: '#7A1A5C' },
  sante:        { l: 'Corps & Santé',       bg: '#EEFAF5', c: '#1A6B4A' },
  metiers:      { l: 'Métiers & Travail',   bg: '#F0F4FF', c: '#2A3A7A' },
  pronoms:      { l: 'Pronoms',             bg: '#F8F0FF', c: '#5A2A8C' },
  conjonctions: { l: 'Conjonctions',        bg: '#FFF0E8', c: '#8C4A1A' },
  proverbes:    { l: 'Proverbes',           bg: '#EAF1FB', c: '#1E3D7A' },
  alphabet:     { l: 'Alphabet',            bg: '#FAEAE8', c: '#7A2D22' },
  autres:       { l: 'Autres',              bg: '#F2F2F2', c: '#505050' },
};

// ── Sections ressources ──
const RES_SECTIONS = {
  podcasts: { l: 'Podcasts gratuits' },
  dicos:    { l: 'Dictionnaires français ↔ Darija' },
  infos:    { l: "Sites d'information" },
  autres:   { l: 'Reddit & autres ressources' },
};

// ── Ressources par défaut ──
const RES_DEFAULT = [
  {id:'r0',sec:'podcasts',name:'Marocain Facile — Cours audio',url:'https://marocain-facile.com/cours-gratuits-de-darija-marocain/',desc:'Cours gratuits en audio et texte, idéal débutants',builtin:true},
  {id:'r1',sec:'podcasts',name:'Arabic With Sam — YouTube',url:'https://www.youtube.com/@ArabicWithSam',desc:'Chaîne YouTube dédiée au darija avec des dialogues du quotidien',builtin:true},
  {id:'r2',sec:'podcasts',name:'Learn Moroccan Arabic — YouTube',url:'https://www.youtube.com/@LearnMoroccanArabic',desc:'Leçons vidéo gratuites centrées prononciation et vocabulaire',builtin:true},
  {id:'r3',sec:'podcasts',name:'ArabicPod101 — Moroccan Arabic',url:'https://www.arabicpod101.com/',desc:'Podcasts audio progressifs, niveau débutant à avancé',builtin:true},
  {id:'r4',sec:'dicos',name:'Marocdico — Dictionnaire en ligne',url:'https://www.marocdico.com/',desc:'Dictionnaire français-darija avec exemples de phrases',builtin:true},
  {id:'r5',sec:'dicos',name:'Freelang — Dictionnaire marocain',url:'https://www.freelang.net/dictionnaire/arabe-marocain.php',desc:'Dictionnaire downloadable et en ligne, très complet',builtin:true},
  {id:'r6',sec:'dicos',name:'Forvo — Prononciation darija',url:'https://fr.forvo.com/languages/ary/',desc:'Prononciations audio par des locuteurs natifs',builtin:true},
  {id:'r7',sec:'dicos',name:'Google Traduction — Arabe',url:'https://translate.google.com/?sl=fr&tl=ar',desc:'Utile pour écriture arabe avec synthèse vocale',builtin:true},
  {id:'r8',sec:'infos',name:'Hespress — Actualités Maroc',url:'https://www.hespress.com/',desc:'Le plus grand site info marocain, articles en darija et arabe',builtin:true},
  {id:'r9',sec:'infos',name:'Goud.ma — Info & société',url:'https://goud.ma/',desc:'Actualités marocaines en darija, très accessible',builtin:true},
  {id:'r10',sec:'infos',name:'Le360 — Bilingue FR/AR',url:'https://fr.le360.ma/',desc:'Média marocain en français et arabe',builtin:true},
  {id:'r11',sec:'infos',name:'2M — Télévision nationale',url:'https://www.2m.ma/',desc:'Chaîne publique marocaine, émissions en darija',builtin:true},
  {id:'r12',sec:'autres',name:'r/Morocco — Subreddit Maroc',url:'https://www.reddit.com/r/Morocco/',desc:'Communauté très active, discussions en darija et français',builtin:true},
  {id:'r13',sec:'autres',name:'r/learnArabic — Apprentissage',url:'https://www.reddit.com/r/learnArabic/',desc:"Ressources et entraide pour apprendre l'arabe",builtin:true},
  {id:'r14',sec:'autres',name:'r/Moroccan — Culture marocaine',url:'https://www.reddit.com/r/Moroccan/',desc:'Discussions culturelles et humour en darija',builtin:true},
  {id:'r15',sec:'autres',name:'r/languagelearning — Darija tips',url:'https://www.reddit.com/r/languagelearning/search/?q=moroccan+darija',desc:"Fils de discussion spécifiques sur l'apprentissage du darija",builtin:true},
];

// ── Cartes de base (285 cartes) ──
const DATA = [
  {id:0,cat:'salutations',fr:'Bonjour',d:'Salam 3alaykoum',a:'السلام عليكم',p:'sa-lam a-lay-koum',n:'Réponse : Wa 3alaykoum salam'},
  {id:1,cat:'salutations',fr:'Bonjour (matin)',d:'Sba7 lkhir',a:'صباح الخير',p:'sba-7 l-khir',n:'Réponse : Sba7 nnor'},
  {id:2,cat:'salutations',fr:'Bonsoir',d:'Msa lkhir',a:'مساء الخير',p:'msa l-khir',n:'Réponse : Msa nnor'},
  {id:3,cat:'salutations',fr:'Comment vas-tu ?',d:'Ki dayr ? / Ki dayra ?',a:'كيداير؟',p:'ki da-yr (h) · ki day-ra (f)',n:'Réponse : Labas, 7amdoulilah'},
  {id:4,cat:'salutations',fr:'Ça va bien, merci',d:'Labas, 7amdoulilah',a:'لاباس الحمد لله',p:'la-bass, 7am-dou-li-lah',n:'Formule universelle, même si rien ne va !'},
  {id:5,cat:'salutations',fr:'Bienvenue !',d:'Mar7ba bik !',a:'مرحبا بيك',p:'mar-7ba bik',n:'Pluriel : Mar7ba bikoum'},
  {id:6,cat:'salutations',fr:'Au revoir',d:'Bslama',a:'بسلامة',p:'bss-lama',n:'Litt. "va en paix"'},
  {id:7,cat:'salutations',fr:"S'il vous plaît",d:'3afak',a:'عفاك',p:'3a-fak',n:'Mot le plus utile du voyage'},
  {id:8,cat:'salutations',fr:'Merci beaucoup',d:'Chokran bzzaf',a:'شكرا بزاف',p:'cho-kran bz-zaf',n:'Réponse : Bla jmil (de rien)'},
  {id:9,cat:'salutations',fr:"D'accord / OK",d:'Wakha',a:'واخا',p:'wa-kha',n:'Le mot le plus utilisé du Maroc !'},
  {id:10,cat:'salutations',fr:"Allez, on y va !",d:'Yalla !',a:'يالا',p:'ya-lla',n:'Suivi de Bismillah avant un trajet'},
  {id:11,cat:'salutations',fr:'Félicitations !',d:'Mabrouk !',a:'مبروك',p:'ma-brouk',n:'Mille félicitations : Alf Mabrouk'},
  {id:12,cat:'salutations',fr:'Bon appétit',d:'Bs7a ou ra7a',a:'بالصحة والراحة',p:'bss-7a ou ra-7a',n:'Réponse : Allah y3tek s7a'},
  {id:13,cat:'salutations',fr:'Bonne nuit',d:'Tsbah 3la kheir',a:'تصبح على خير',p:'tsba-7 3la khir',n:'Réponse : Wa nta kheir'},
  {id:14,cat:'salutations',fr:'Comment va la famille ?',d:'Kif la3ila ?',a:'كيف العيلة؟',p:'kif la-3i-la',n:'Demande très appréciée en arrivant'},
  {id:15,cat:'salutations',fr:'Ça fait longtemps !',d:'Bzzaf ma cheftek !',a:'بزاف ما شفتك',p:'bz-zaf ma chef-tek',n:"Litt. \"longtemps que je ne t'ai pas vu\""},
  {id:16,cat:'salutations',fr:'Je suis content de te voir',d:'Far7an bchoftek',a:'فرحان بشوفتك',p:'far-7an bchof-tek',n:'Far7ana pour une femme'},
  {id:17,cat:'salutations',fr:'Pas de souci !',d:'Ma kaynch mochkil !',a:'ماكاينش مشكيل',p:'ma kayn-ch moch-kil',n:'Réponse rassurante très courante'},
  {id:18,cat:'salutations',fr:'Avec plaisir',d:'B kol mamnouniya',a:'بكل ممنونية',p:'b kol mam-nou-ni-ya',n:'Ton formel et chaleureux'},
  {id:19,cat:'salutations',fr:'Je suis désolé(e)',d:'Smah liya',a:'سماح ليا',p:'sma-7 li-ya',n:''},
  {id:20,cat:'salutations',fr:'Prenez soin de vous',d:'Allah y7fdek',a:'الله يحفظك',p:'al-lah y7f-dek',n:'Pluriel : Allah y7fdkom'},
  {id:21,cat:'salutations',fr:'On se revoit bientôt !',d:'Ghadi nchoufou b3d !',a:'غادي نشوفو بعد',p:'gha-di ncho-fou b3d',n:'Très souvent dit en partant'},
  {id:22,cat:'questions',fr:"Comment tu t'appelles ?",d:'Achno smiytek ?',a:'أشنو سميتك؟',p:'ach-no smi-y-tek',n:"Je m'appelle : Smiyti [prénom]"},
  {id:23,cat:'questions',fr:'Que veut dire ce mot ?',d:'Achno ka y3ni hada ?',a:'أشنو كيعني هادا؟',p:'ach-no ka y3-ni ha-da',n:'Super utile pour apprendre sur le vif'},
  {id:24,cat:'questions',fr:"Qu'est-ce que c'est ?",d:'Achno hada ?',a:'أشنو هادا؟',p:'ach-no ha-da',n:'Hada (m.) / Hadi (f.)'},
  {id:25,cat:'questions',fr:'Qui est-ce ?',d:'Chkoun hada ?',a:'شكون هادا؟',p:'chk-oun ha-da',n:'Pour apprendre les prénoms de la famille'},
  {id:26,cat:'questions',fr:"Où va-t-on ?",d:'Fain ghadin ?',a:'فاين غادين؟',p:'fa-in gha-din',n:'Je vais : Ana ghadi'},
  {id:27,cat:'questions',fr:'Où sont les toilettes ?',d:'Finahiya twalit ?',a:'فيناهي الطواليط؟',p:'fi-na-hi-ya twa-lit',n:'Aussi : Bit lma'},
  {id:28,cat:'questions',fr:'Combien ça coûte ?',d:'Ch7al hada ?',a:'شحال هادا؟',p:'ch7-al ha-da',n:"Pas d'argent : Ma 3andich flous"},
  {id:29,cat:'questions',fr:'Tu parles français ?',d:'Ka thDar lfransawiya ?',a:'كتهضر الفرنساوية؟',p:'ka th-dar l-fran-sa-wi-ya',n:'Je ne parle pas arabe : Ma ka nhDarsh l3arbiya'},
  {id:30,cat:'questions',fr:'Je ne comprends pas',d:'Ma fhamtch',a:'ما فهمتش',p:'ma fham-tch',n:'Répète : 3awd 3afak'},
  {id:31,cat:'questions',fr:'Tu as faim ?',d:'Wach fik jou3 ?',a:'واش فيك الجوع؟',p:'wach fik jou-3',n:"J'ai faim : Fiya jou3 · soif : Fiya la3Tach"},
  {id:32,cat:'questions',fr:'Quel âge as-tu ?',d:'Ch7al f 3omrek ?',a:'شحال في عمرك؟',p:'ch7-al f 3om-rek',n:"J'ai X ans : 3andi X snin"},
  {id:33,cat:'questions',fr:"D'où viens-tu ?",d:'Mnin nta ?',a:'منين نتا؟',p:'mnin nta',n:'Féminin : Mnin nti ?'},
  {id:34,cat:'questions',fr:'Tu peux répéter ?',d:'3awd 3afak ?',a:'عاود عفاك؟',p:'3awd 3a-fak',n:'Formule douce'},
  {id:35,cat:'questions',fr:'Comment dit-on X en darija ?',d:'Kifach tgoul X b darija ?',a:'كيفاش تقول بالدارجة؟',p:'ki-fach tgoul b da-ri-ja',n:'Ultra-utile pour progresser vite'},
  {id:36,cat:'questions',fr:"C'est loin ?",d:'Wach b3id ?',a:'واش بعيد؟',p:'wach b3id',n:"C'est près : Wach qrib ?"},
  {id:37,cat:'questions',fr:'À quelle heure ?',d:'F chhal sa3a ?',a:'فشحال الساعة؟',p:'f ch7-al sa-3a',n:'Il est X heures : Sa3a X'},
  {id:38,cat:'compliments',fr:"C'est délicieux !",d:'Bnin bzzaf !',a:'بنين بزاف',p:'bni-n bz-zaf',n:'À dire à chaque plat de la belle-mère !'},
  {id:39,cat:'compliments',fr:'Ta cuisine est excellente !',d:'Tiyab dialek mezyan !',a:'الطياب ديالك مزيان',p:'ti-yab dia-lek mez-yan',n:'Fera sourire toute la belle-famille'},
  {id:40,cat:'compliments',fr:'Que Dieu te bénisse',d:'Barak Allahou fik',a:'بارك الله فيك',p:'ba-rak al-la-hou fik',n:'Réponse après un Mabrouk ou un cadeau'},
  {id:41,cat:'compliments',fr:"Je t'aime",d:'Kanbghik',a:'كنبغيك',p:'kan-bghik',n:'Je vous aime (pluriel) : Kanbghikoum'},
  {id:42,cat:'compliments',fr:'Tu me manques',d:'Twe77eshtek',a:'توحشتك',p:'twe-77-esh-tek',n:'Très touchant à dire à la belle-famille'},
  {id:43,cat:'compliments',fr:'Mon chéri / ma chérie',d:'Hbib / Hbiba diali',a:'حبيب / حبيبة ديالي',p:'7bib / 7biba dia-li',n:'Aussi : Kbida (mon petit cœur)'},
  {id:44,cat:'compliments',fr:"C'est très beau !",d:'Zwin bzzaf !',a:'زوين بزاف',p:'zwi-n bz-zaf',n:'Zwina (fém.) · maison, robe, paysage…'},
  {id:45,cat:'compliments',fr:'Tout est parfait ici',d:'Kolchi mzien',a:'كلشي مزيان',p:'kol-chi mzi-en',n:'Expression positive très courante'},
  {id:46,cat:'compliments',fr:'Tu es très gentil(le)',d:'Nta mezyan bzzaf',a:'نتا مزيان بزاف',p:'nta mez-yan bz-zaf',n:'Nti mezyana (féminin)'},
  {id:47,cat:'compliments',fr:'Ta maison est magnifique',d:'Dartek zwiniya bzzaf',a:'دارتك زوينية بزاف',p:'dar-tek zwi-ni-ya bz-zaf',n:'Compliment qui fait toujours plaisir'},
  {id:48,cat:'compliments',fr:'Tes enfants sont adorables',d:'Wladek zwinin bzzaf',a:'ولادك زوينين بزاف',p:'wla-dek zwi-nin bz-zaf',n:'Incontournable chez la belle-famille'},
  {id:49,cat:'compliments',fr:'Tu as très bon goût',d:'3andek daw9a mezyana',a:'عندك ذوقة مزيانة',p:'3an-dek daw-9a mez-ya-na',n:'Pour une tenue, un intérieur…'},
  {id:50,cat:'humour',fr:'Tu voulais arriver tôt ! (ironie)',d:'Bghiti tji bekri !',a:'بغيتي تجي بكري',p:'bghi-ti tji bek-ri',n:'Avec le sourire pour un retardataire'},
  {id:51,cat:'humour',fr:'Situation qui empire',d:'Zit 3la zit !',a:'زيت على زيت',p:'zit 3la zit',n:'Huile sur huile'},
  {id:52,cat:'humour',fr:'Les poissons volent ! (crédule)',d:'Galek l7out kaytir !',a:'قالك الحوت كيطير',p:'ga-lek l-7out kay-tir',n:"Pour quelqu'un de trop naïf"},
  {id:53,cat:'humour',fr:'Pas maintenant, pas maintenant…',d:'Machi daba, machi daba',a:'ماشي دابا ماشي دابا',p:'ma-chi da-ba',n:'Réponse universelle à toute urgence !'},
  {id:54,cat:'humour',fr:'Doucement, doucement',d:'Chwiya chwiya',a:'شوية شوية',p:'chwi-ya chwi-ya',n:'Philosophie de vie : rien ne presse'},
  {id:55,cat:'humour',fr:"Ce n'est pas un plat, c'est du piment !",d:'Hada machi chebs !',a:'هادا ماشي شبس',p:'ha-da ma-chi chebs',n:"Pour commenter l'abus d'épices"},
  {id:56,cat:'humour',fr:"Inch'Allah (réponse à tout)",d:"Inch'Allah",a:'إن شاء الله',p:'inch-al-lah',n:'Peut vouloir dire oui, non, ou peut-être…'},
  {id:57,cat:'humour',fr:'Peut-être… (= probablement non)',d:'Imkin',a:'إمكن',p:'im-kin',n:'Le "on verra" marocain'},
  {id:58,cat:'humour',fr:'Mange ! Tu es trop maigre !',d:'Kol kol, nta 3fik !',a:'كول كول نتا عفيك',p:'kol kol nta 3fiq',n:'La belle-mère marocaine en une phrase'},
  {id:59,cat:'humour',fr:'Il est arrivé comme une mariée',d:'Ja bhal l3aroussa',a:'جا بهال العروسة',p:'ja bhal l3a-rous-sa',n:"Pour quelqu'un en retard avec style"},
  {id:60,cat:'humour',fr:'Mon estomac fait la grève',d:'Kershti qa3da teb7er',a:'كرشتي قاعدة تبحر',p:'ker-chti qa3-da teb-7er',n:'J\'ai très faim — litt. "mon ventre navigue"'},
  {id:61,cat:'humour',fr:"Je suis venu, j'ai vu, j'ai mangé",d:'Jit, cheft, klit',a:'جيت، شفت، كليت',p:'jit cheft klit',n:'Version marocaine de César'},
  {id:62,cat:'humour',fr:'Dieu merci pour tout',d:'7amdoulilah 3la kol 7al',a:'الحمد لله على كل حال',p:'7am-dou-li-lah 3la kol 7al',n:'Acceptation totale et philosophique'},
  {id:63,cat:'humour',fr:'Le thé est prêt depuis une heure !',d:'Atay jah men sa3a !',a:'أتاي جاء من ساعة',p:'a-tay jah men sa-3a',n:"L'hôte marocain n'attend pas"},
  {id:64,cat:'famille',fr:'Père',d:'Bba / Walid',a:'بابا / والد',p:'bba / wa-lid',n:'Bba est plus affectueux'},
  {id:65,cat:'famille',fr:'Mère',d:'Mma / Walida',a:'ماما / والدة',p:'mma / wa-li-da',n:'Mma est plus affectueux'},
  {id:66,cat:'famille',fr:'Frère',d:'Khou',a:'خو',p:'khou',n:'Mon frère : Khoya'},
  {id:67,cat:'famille',fr:'Sœur',d:'Khtoh',a:'ختو',p:'kh-toh',n:'Ma sœur : Khti'},
  {id:68,cat:'famille',fr:'Grand-père',d:'Jedd',a:'جد',p:'jedd',n:'Mon grand-père : Jeddi'},
  {id:69,cat:'famille',fr:'Grand-mère',d:'Jeddah',a:'جدة',p:'jed-da',n:'Ma grand-mère : Jeddati'},
  {id:70,cat:'famille',fr:'Oncle paternel',d:'3amm',a:'عم',p:'3amm',n:'Mon oncle : 3ammi · très respectueux'},
  {id:71,cat:'famille',fr:'Tante paternelle',d:'3amma',a:'عمة',p:'3am-ma',n:'Ma tante : 3ammti'},
  {id:72,cat:'famille',fr:'Oncle maternel',d:'Khal',a:'خال',p:'khal',n:'Mon oncle : Khali'},
  {id:73,cat:'famille',fr:'Tante maternelle',d:'Khala',a:'خالة',p:'kha-la',n:'Ma tante : Khalti'},
  {id:74,cat:'famille',fr:'Belle-mère (mère du conjoint)',d:'Hmoh',a:'حموة',p:'7-moh',n:'Terme affectueux et respectueux'},
  {id:75,cat:'famille',fr:'Beau-père (père du conjoint)',d:'Nassib / 3amm',a:'نسيب',p:'nas-sib',n:"Nassib = lien d'alliance"},
  {id:76,cat:'famille',fr:'Mari',d:'Rajel',a:'راجل',p:'ra-jel',n:'Mon mari : Rajli'},
  {id:77,cat:'famille',fr:'Femme / Épouse',d:'Mra',a:'مرا',p:'mra',n:'Ma femme : Mrati'},
  {id:78,cat:'famille',fr:'Fils / Garçon',d:'Weld',a:'ولد',p:'weld',n:'Mon fils : Wlidi'},
  {id:79,cat:'famille',fr:'Fille',d:'Bnet',a:'بنت',p:'bnet',n:'Ma fille : Bniti'},
  {id:80,cat:'famille',fr:'Famille',d:'3ila',a:'عيلة',p:'3i-la',n:'Grande famille : 3ila kbira'},
  {id:81,cat:'maison',fr:'Maison',d:'Dar',a:'دار',p:'dar',n:'Ma maison : Darti'},
  {id:82,cat:'maison',fr:'Salon (pièce de réception)',d:'Bit jlous',a:'بيت الجلوس',p:'bit jlous',n:'La pièce principale chez les Fassis'},
  {id:83,cat:'maison',fr:'Cuisine',d:'Kouzina',a:'كوزينة',p:'kou-zi-na',n:'Emprunt au français'},
  {id:84,cat:'maison',fr:'Pain (galette marocaine)',d:'Khobz',a:'خبز',p:'khobz',n:'Présent à chaque repas'},
  {id:85,cat:'maison',fr:'Couscous du vendredi',d:'Kskss dyal ljem3a',a:'كسكس ديال الجمعة',p:'kskss dyal l-jem-3a',n:'Tradition sacrée · le vendredi après la prière'},
  {id:86,cat:'maison',fr:'Tajine',d:'Tajin',a:'طاجين',p:'ta-jin',n:'Le plat marocain par excellence'},
  {id:87,cat:'maison',fr:'Harira (soupe)',d:'Harira',a:'حريرة',p:'ha-ri-ra',n:'Soupe de rupture du jeûne'},
  {id:88,cat:'maison',fr:'Thé à la menthe',d:'Atay b nana',a:'أتاي بالنعناع',p:'a-tay b na-na',n:'Refuser le thé est très mal vu !'},
  {id:89,cat:'maison',fr:'Eau',d:'L-ma',a:'الما',p:'l-ma',n:"Un verre d'eau : Kass d l-ma"},
  {id:90,cat:'maison',fr:'Épices',d:'Hwayj',a:'حوايج',p:'7wa-yej',n:'Le mélange marocain est unique'},
  {id:91,cat:'maison',fr:"C'est prêt !",d:'Wajad !',a:'واجد',p:'wa-jad',n:'Signal pour passer à table'},
  {id:92,cat:'maison',fr:'Sers-toi !',d:'Dir rasek !',a:'دير راسك',p:'dir ra-sek',n:'Litt. "fais-toi" · invitation à se servir'},
  {id:93,cat:'maison',fr:'Encore un peu ?',d:'Zid chwiya ?',a:'زيد شوية؟',p:'zid chwi-ya',n:'On insiste toujours au Maroc !'},
  {id:94,cat:'maison',fr:'Je suis rassasié(e)',d:'Chb3t, 7amdoulilah',a:'شبعت الحمد لله',p:'chb3t 7am-dou-li-lah',n:'Toujours ajouter 7amdoulilah'},
  {id:95,cat:'ville',fr:'Médina (vieille ville)',d:'Mdina',a:'المدينة',p:'mdi-na',n:'Fès el-Bali est la plus ancienne médina'},
  {id:96,cat:'ville',fr:'Souk (marché)',d:'Souk',a:'السوق',p:'souk',n:'Chaque artisanat a son souk à Fès'},
  {id:97,cat:'ville',fr:'Rue / Ruelle',d:'Zanqa',a:'زنقة',p:'zan-qa',n:'Les zanqas de Fès sont labyrinthiques !'},
  {id:98,cat:'ville',fr:'Taxi',d:'Taxi',a:'طاكسي',p:'tak-si',n:'Petit taxi : ville · Grand taxi : entre villes'},
  {id:99,cat:'ville',fr:'À gauche',d:'Liser',a:'ليسر',p:'li-ser',n:'Tourne à gauche : Dir liser'},
  {id:100,cat:'ville',fr:'À droite',d:'Limine',a:'ليمين',p:'li-min',n:'Tourne à droite : Dir limine'},
  {id:101,cat:'ville',fr:'Tout droit',d:'Niyshan',a:'نيشان',p:'niy-shan',n:'Sir niyshan'},
  {id:102,cat:'ville',fr:'Je suis perdu(e)',d:'T7t',a:'تهت',p:'t7t',n:'T7tat pour une femme'},
  {id:103,cat:'ville',fr:'Tannerie',d:'Dabbagha',a:'الدباغة',p:'dab-ba-gha',n:'Spectacle unique à Fès'},
  {id:104,cat:'ville',fr:'Riad',d:'Riad',a:'رياض',p:'ri-yad',n:'Maison traditionnelle avec cour intérieure'},
  {id:105,cat:'chiffres',fr:'Un',d:'Wa7ed',a:'واحد',p:'wa-7ed',n:''},
  {id:106,cat:'chiffres',fr:'Deux',d:'Jouj',a:'جوج',p:'jouj',n:''},
  {id:107,cat:'chiffres',fr:'Trois',d:'Tlata',a:'تلاتة',p:'tla-ta',n:''},
  {id:108,cat:'chiffres',fr:'Quatre',d:'Rb3a',a:'ربعة',p:'rb-3a',n:''},
  {id:109,cat:'chiffres',fr:'Cinq',d:'Khmsa',a:'خمسة',p:'khm-sa',n:''},
  {id:110,cat:'chiffres',fr:'Six',d:'Stta',a:'ستة',p:'stta',n:''},
  {id:111,cat:'chiffres',fr:'Sept',d:'Sb3a',a:'سبعة',p:'sb-3a',n:''},
  {id:112,cat:'chiffres',fr:'Huit',d:'Tmnya',a:'تمنية',p:'tmn-ya',n:''},
  {id:113,cat:'chiffres',fr:'Neuf',d:'Ts3oud',a:'تسعود',p:'ts-3oud',n:''},
  {id:114,cat:'chiffres',fr:'Dix',d:'3achra',a:'عشرة',p:'3ach-ra',n:'Vingt : 3achrin · Cent : Miya'},
  {id:115,cat:'chiffres',fr:"Aujourd'hui",d:'Lyoum',a:'اليوم',p:'l-youm',n:''},
  {id:116,cat:'chiffres',fr:'Demain',d:'Ghedda',a:'غدة',p:'ghed-da',n:''},
  {id:117,cat:'chiffres',fr:'Hier',d:'Lbar7',a:'البارح',p:'l-bar-7',n:''},
  {id:118,cat:'chiffres',fr:'Quelle heure est-il ?',d:'Chhal sa3a daba ?',a:'شحال الساعة دابا؟',p:'ch7-al sa-3a da-ba',n:'Il est 3h : Sa3a tlata'},
  {id:119,cat:'chiffres',fr:'Maintenant / Tout de suite',d:'Daba daba !',a:'دابا دابا',p:'da-ba da-ba',n:'Répété = vraie urgence'},
  {id:120,cat:'fruits',fr:'Orange / Mandarine',d:'Limo / Litchina',a:'الليمو / الليتشينا',p:'li-mo',n:'Litchina = mandarine marocaine'},
  {id:121,cat:'fruits',fr:'Pastèque',d:'Dellah',a:'الدلاح',p:'del-la7',n:"Fruit de l'été marocain"},
  {id:122,cat:'fruits',fr:'Datte',d:'Tmar',a:'التمر',p:'tmar',n:"Offertes à l'arrivée avec du lait"},
  {id:123,cat:'fruits',fr:'Olive',d:'Zitoun',a:'الزيتون',p:'zi-toun',n:'Présentes sur toutes les tables'},
  {id:124,cat:'fruits',fr:'Tomate',d:'Matisha',a:'الماتيشا',p:'ma-ti-sha',n:'Base de la cuisine marocaine'},
  {id:125,cat:'fruits',fr:'Oignon',d:'Bsel',a:'البصل',p:'bsel',n:'Indispensable dans le tajine'},
  {id:126,cat:'fruits',fr:'Ail',d:'Touma',a:'الثوم',p:'tou-ma',n:'Essentiel dans la cuisine de Fès'},
  {id:127,cat:'fruits',fr:'Carotte',d:'Khizou',a:'الخيزو',p:'khi-zou',n:'Légume du couscous classique'},
  {id:128,cat:'fruits',fr:'Pomme de terre',d:'Batata',a:'البطاطا',p:'ba-ta-ta',n:'Légume le plus consommé au Maroc'},
  {id:129,cat:'fruits',fr:'Courgette',d:'Qr3a',a:'القرعة',p:'qr-3a',n:'Incontournable dans le couscous'},
  {id:130,cat:'fruits',fr:'Coriandre',d:'Qzbour',a:'القزبور',p:'qz-bour',n:'Arôme signature de la cuisine marocaine'},
  {id:131,cat:'religion',fr:'Ramadan Karim',d:'Ramadan Karim',a:'رمضان كريم',p:'ra-ma-dan ka-rim',n:'Réponse : Allahu Akram'},
  {id:132,cat:'religion',fr:'Ramadan Moubarak',d:'Ramadan Moubarak',a:'رمضان مبارك',p:'ra-ma-dan mou-ba-rak',n:"Vœu dès l'annonce du croissant"},
  {id:133,cat:'religion',fr:'Bon iftar !',d:'Ftor mabrouk',a:'فطور مبروك',p:'ftor mab-rouk',n:'Au moment de la rupture du jeûne'},
  {id:134,cat:'religion',fr:"Bonne fête de l'Aïd !",d:'3id Moubarak !',a:'عيد مبارك',p:'3id mou-ba-rak',n:"Pour l'Aïd el-Fitr et l'Aïd el-Adha"},
  {id:135,cat:'religion',fr:'Aïd el-Fitr (fin du Ramadan)',d:'3id s-sghir',a:'عيد الصغير',p:'3id s-sghir',n:'Litt. "la petite fête"'},
  {id:136,cat:'religion',fr:'Aïd el-Adha (fête du sacrifice)',d:'3id l-kbir',a:'عيد الكبير',p:'3id l-kbir',n:'Litt. "la grande fête" · sacrifice du mouton'},
  {id:137,cat:'religion',fr:'Dieu soit loué',d:'7amdoulilah',a:'الحمد لله',p:'7am-dou-li-lah',n:'Après tout repas, bonne nouvelle, effort'},
  {id:138,cat:'religion',fr:'Si Dieu le veut',d:"Inch'Allah",a:'إن شاء الله',p:'inch-al-lah',n:'Incontournable dans toute promesse'},
  {id:139,cat:'religion',fr:'Au nom de Dieu',d:'Bismillah',a:'بسم الله',p:'bis-mil-lah',n:'Avant de manger, démarrer un trajet'},
  {id:140,cat:'religion',fr:'Dieu est grand',d:'Allahou Akbar',a:'الله أكبر',p:'al-la-hou ak-bar',n:'Expression de foi, joie ou émerveillement'},
  {id:141,cat:'religion',fr:'Que Dieu vous garde',d:'Allah y7fdkom',a:'الله يحفظكم',p:'al-lah y7fd-kom',n:'Adieu chaleureux à toute la famille'},
  {id:142,cat:'religion',fr:'La mosquée Al-Qarawiyyin',d:'Jami3 l-Qarawiyyin',a:'جامع القرويين',p:'ja-mi3 l-qa-ra-wi-yin',n:'La plus ancienne université du monde · Fès 859'},
  {id:143,cat:'proverbes',fr:'Qui veut le miel supporte les piqûres',d:'Li bgha la3ssel, isber 3la qriss n7el',a:'اللي بغا العسل يصبر على قرص النحل',p:'li bgha la3-ssel is-ber 3la qriss n7el',n:'Leçon de persévérance'},
  {id:144,cat:'proverbes',fr:'Une seule main ne peut applaudir',d:'Yed wa7da ma katseffe9ch',a:'يد واحدة ما كتصفقش',p:'yed wa-7da ma kat-seffe9-ch',n:'La solidarité familiale avant tout'},
  {id:145,cat:'proverbes',fr:'Qui se dépêche finit en retard',d:'Zreb, t3ettel',a:'زرب تعطل',p:'zreb t-3et-tel',n:'Antidote à la précipitation'},
  {id:146,cat:'proverbes',fr:'La patience est la clé de la délivrance',d:'Sbar miftah lfaraj',a:'الصبر مفتاح الفرج',p:'sbar mif-tah l-fa-raj',n:'Sbar (patience) est central dans la culture marocaine'},
  {id:147,cat:'alphabet',fr:'Alif · voyelle longue',d:'alif',a:'ا',p:'a / â',n:'1ère lettre'},
  {id:148,cat:'alphabet',fr:'Ba · son b',d:'ba',a:'ب',p:'b',n:'ex : bnin · bslama'},
  {id:149,cat:'alphabet',fr:'Ta · son t',d:'ta',a:'ت',p:'t',n:'ex : twalit'},
  {id:150,cat:'alphabet',fr:'Jim · son j',d:'jim',a:'ج',p:'j',n:'ex : jou3 (faim)'},
  {id:151,cat:'alphabet',fr:'Ha · h fort soufflé · noté 7',d:'ha',a:'ح',p:'7',n:'Inexistant en français ! ex : 7amdoulilah'},
  {id:152,cat:'alphabet',fr:'Kha · son kh (Bach)',d:'kha',a:'خ',p:'kh',n:'ex : khir (bien)'},
  {id:153,cat:'alphabet',fr:'Dal · son d',d:'dal',a:'د',p:'d',n:'ex : daba (maintenant)'},
  {id:154,cat:'alphabet',fr:'Ra · r roulé espagnol',d:'ra',a:'ر',p:'r roulé',n:'ex : ra7a (repos)'},
  {id:155,cat:'alphabet',fr:'Zin · son z',d:'zin',a:'ز',p:'z',n:'ex : zwin (beau)'},
  {id:156,cat:'alphabet',fr:'Sin · son s doux',d:'sin',a:'س',p:'s',n:'ex : salam · sbar'},
  {id:157,cat:'alphabet',fr:'Chin · son ch',d:'chin',a:'ش',p:'ch',n:'ex : chokran · chwiya'},
  {id:158,cat:'alphabet',fr:'Sad · s emphatique',d:'sad',a:'ص',p:'S (fond de la bouche)',n:'ex : Sba7'},
  {id:159,cat:'alphabet',fr:'Ain · contraction gorge · noté 3',d:'ain',a:'ع',p:'3 (gorge)',n:'ex : 3afak · 3andek'},
  {id:160,cat:'alphabet',fr:'Ghain · r grasseyé parisien',d:'ghain',a:'غ',p:'gh',n:'ex : ghadin (on va)'},
  {id:161,cat:'alphabet',fr:'Fa · son f',d:'fa',a:'ف',p:'f',n:'ex : flous (argent)'},
  {id:162,cat:'alphabet',fr:'Qaf · q guttural · souvent g',d:'qaf',a:'ق',p:'q / g',n:'ex : qriss'},
  {id:163,cat:'alphabet',fr:'Kaf · son k',d:'kaf',a:'ك',p:'k',n:'ex : kanbghik'},
  {id:164,cat:'alphabet',fr:'Lam · son l',d:'lam',a:'ل',p:'l',n:'ex : labas · lkhir'},
  {id:165,cat:'alphabet',fr:'Mim · son m',d:'mim',a:'م',p:'m',n:'ex : mabrouk'},
  {id:166,cat:'alphabet',fr:'Nun · son n',d:'nun',a:'ن',p:'n',n:'ex : nnor (la lumière)'},
  {id:167,cat:'alphabet',fr:'Ha léger · h doux',d:'ha léger',a:'ه',p:'h',n:'ex : hada (celui-ci)'},
  {id:168,cat:'alphabet',fr:'Waw · w ou voyelle ou',d:'waw',a:'و',p:'w / ou',n:'ex : wakha'},
  {id:169,cat:'alphabet',fr:'Ya · y ou voyelle i',d:'ya',a:'ي',p:'y / i',n:'ex : yalla · diali'},
  {id:170,cat:'emotions',fr:'Je suis heureux / heureuse',d:'Ana mbsout / mbsouta',a:'أنا مبسوط / مبسوطة',p:'a-na mb-sout',n:'Mbsouta pour une femme · équivalent de "je suis content"'},
  {id:171,cat:'emotions',fr:'Je suis très heureux / heureuse',d:'Ana far7an / far7ana bzzaf',a:'أنا فرحان بزاف',p:'a-na far-7an bz-zaf',n:'Far7ana pour une femme · expression de bonheur intense'},
  {id:172,cat:'emotions',fr:"Ça m'a fait plaisir",d:'Hadi fr7atni',a:'هادي فرحتني',p:'ha-di fr-7at-ni',n:'Après un cadeau, une bonne nouvelle'},
  {id:173,cat:'emotions',fr:'Je me sens bien',d:'Kanhs bikhir',a:'كنحس بخير',p:'kan-7ss bi-khir',n:'Expression générale de bien-être'},
  {id:174,cat:'emotions',fr:'Je suis triste',d:'Ana 7zin / 7zina',a:'أنا حزين / حزينة',p:'a-na 7zin',n:'7zina pour une femme'},
  {id:175,cat:'emotions',fr:'Mon cœur est lourd',d:'Qlbi mghomoum',a:'قلبي مغموم',p:'qlbi mgho-moum',n:'Expression de tristesse profonde'},
  {id:176,cat:'emotions',fr:'Tu me manques',d:'Twa77ashtk',a:'توحشتك',p:'twa-77-ash-tk',n:"Expression d'attachement fort, très utilisée en famille"},
  {id:177,cat:'emotions',fr:'Je suis en colère',d:'Ana m3assab / m3assaba',a:'أنا معصب / معصبة',p:'a-na m3as-sab',n:'M3assaba pour une femme'},
  {id:178,cat:'emotions',fr:'Laisse-moi tranquille',d:'Khllini f 7ali',a:'خليني في حالي',p:'khli-ni f 7a-li',n:"Demande d'espace, ton ferme mais courant"},
  {id:179,cat:'emotions',fr:'Je suis fatigué(e) de ça',d:'T3ibt mn hadi l7ala',a:'تعبت من هادي الحالة',p:'t3ibt mn ha-di l-7a-la',n:'Épuisement moral ou physique'},
  {id:180,cat:'emotions',fr:'Je suis inquiet / inquiète',d:'Ana mchouwwesh / mchouwwesha',a:'أنا مشوش / مشوشة',p:'a-na mchouw-wesh',n:'Stress ou inquiétude'},
  {id:181,cat:'emotions',fr:"J'ai peur",d:'Ana khayf / khayfa',a:'أنا خايف / خايفة',p:'a-na khayf',n:'Khayfa pour une femme'},
  {id:182,cat:'emotions',fr:"C'est incroyable !",d:'Hadi wa3ra bzzaf !',a:'هادي واعرة بزاف',p:'ha-di wa3-ra bz-zaf',n:'Étonnement positif'},
  {id:183,cat:'emotions',fr:'Vraiment ? / Sérieusement ?',d:'Bss7 ?',a:'بصح؟',p:'bss-7',n:'Doute ou surprise mêlée'},
  {id:184,cat:'emotions',fr:"Ça m'a choqué(e)",d:'Hadi sdmttni',a:'هادي صدمتني',p:'ha-di sdm-tni',n:'Choc émotionnel fort'},
  {id:185,cat:'emotions',fr:'Je ne peux plus',d:'Ma bqitsh nqdr',a:'ما بقيتش نقدر',p:'ma bqi-tsh nq-dr',n:"Expression d'épuisement ou de découragement"},
  {id:186,cat:'emotions',fr:'Je suis fier / fière de toi',d:'Ana fakhour / fakhouriya bik',a:'أنا فاخور بيك',p:'a-na fa-khour bik',n:'Fakhouriya pour une femme · très utilisé pour encourager'},
  {id:187,cat:'emotions',fr:'Ça ne fait rien / tant pis',d:'Ma3lich',a:'معليش',p:'ma-3-lich',n:"Philosophie marocaine de l'acceptation · très courant"},
  {id:188,cat:'emotions',fr:"C'est bon / c'est fini",d:'Safi',a:'صافي',p:'sa-fi',n:"Pour clore une discussion ou confirmer que c'est réglé"},
  {id:189,cat:'emotions',fr:'Courage !',d:'Qawi rasek !',a:'قوي راسك',p:'qa-wi ra-sek',n:'Litt. "renforce ta tête" · expression d\'encouragement'},
  {id:190,cat:'sante',fr:'Tête',d:'Ras',a:'راس',p:'ras',n:"J'ai mal à la tête : Darni rasi"},
  {id:191,cat:'sante',fr:'Visage',d:'Woujah',a:'وجه',p:'wou-jah',n:''},
  {id:192,cat:'sante',fr:'Yeux',d:'3inine',a:'عينين',p:'3i-ni-ne',n:'Un œil : 3ine'},
  {id:193,cat:'sante',fr:'Nez',d:'Nif',a:'نيف',p:'nif',n:''},
  {id:194,cat:'sante',fr:'Bouche',d:'Fomm',a:'فم',p:'fomm',n:''},
  {id:195,cat:'sante',fr:'Dents',d:'Snan',a:'سنان',p:'snan',n:'Une dent : Sna'},
  {id:196,cat:'sante',fr:'Oreilles',d:'Woudnine',a:'ودنين',p:'woud-ni-ne',n:'Une oreille : Ouden'},
  {id:197,cat:'sante',fr:'Cheveux',d:'Ch3ar',a:'شعر',p:'ch3ar',n:''},
  {id:198,cat:'sante',fr:'Cou',d:'Reg',a:'رقبة',p:'reg',n:''},
  {id:199,cat:'sante',fr:'Épaule',d:'Ktef',a:'كتف',p:'ktef',n:''},
  {id:200,cat:'sante',fr:'Dos',d:'Dhr',a:'ضهر',p:'dhr',n:"J'ai mal au dos : Darni dhri"},
  {id:201,cat:'sante',fr:'Ventre',d:'Kerch',a:'كرش',p:'kerch',n:"J'ai mal au ventre : Darni kerchi"},
  {id:202,cat:'sante',fr:'Main',d:'Yedd',a:'يد',p:'yedd',n:'Les mains : Iyyadine'},
  {id:203,cat:'sante',fr:'Jambe',d:'Rejl',a:'رجل',p:'rejl',n:'Les jambes : Rejline'},
  {id:204,cat:'sante',fr:'Je suis malade',d:'Ana mriD / mriDa',a:'أنا مريض / مريضة',p:'a-na mri-D',n:'MriDa pour une femme'},
  {id:205,cat:'sante',fr:"J'ai de la fièvre",d:'Fiya skhana',a:'فيا السخانة',p:'fi-ya skha-na',n:'Appelle le médecin : 3ayyet 3la Tbib'},
  {id:206,cat:'sante',fr:"J'ai mal ici",d:'Kaydarni hna',a:'كيدارني هنا',p:'kay-dar-ni hna',n:"En montrant l'endroit — très utile chez le médecin"},
  {id:207,cat:'sante',fr:'Médecin',d:'Tbib',a:'طبيب',p:'tbi-b',n:'Médecin femme : Tbiba'},
  {id:208,cat:'sante',fr:'Pharmacie',d:'Farmasyan',a:'فارماسيان',p:'far-ma-syan',n:'Médicament : Dwa'},
  {id:209,cat:'sante',fr:'Hôpital',d:'Sbitar',a:'سبيتار',p:'sbi-tar',n:'Emprunt de l\'espagnol "hospital"'},
  {id:210,cat:'sante',fr:'Appelez une ambulance !',d:'3iyyet 3la ambulance !',a:'عيط على الأمبولانس',p:'3iy-yet 3la am-bou-lans',n:'Urgence médicale'},
  {id:211,cat:'metiers',fr:'Médecin',d:'Tbib / Tbiba',a:'طبيب / طبيبة',p:'tbi-b / tbi-ba',n:'Fach ka tkhddem ? = Qu\'est-ce que tu fais dans la vie ?'},
  {id:212,cat:'metiers',fr:'Enseignant(e)',d:'Oustad / Oustada',a:'أستاد / أستادة',p:'ous-tad',n:"Terme très respectueux, aussi utilisé pour interpeller quelqu'un"},
  {id:213,cat:'metiers',fr:'Ingénieur / Architecte',d:'Mohandis / Mohandisa',a:'مهندس / مهندسة',p:'mo-han-dis',n:''},
  {id:214,cat:'metiers',fr:'Avocat(e)',d:'Mo7ami / Mo7amiya',a:'محامي / محامية',p:'mo-7a-mi',n:''},
  {id:215,cat:'metiers',fr:'Infirmier / Infirmière',d:'Fermli / Fermliya',a:'فيرملي / فيرملية',p:'ferm-li',n:''},
  {id:216,cat:'metiers',fr:'Policier',d:'Boulisi',a:'بوليسي',p:'bou-li-si',n:'La police : la boulisa'},
  {id:217,cat:'metiers',fr:'Boucher',d:'Gezzer / Gezzera',a:'جزار / جزارة',p:'gez-zer',n:''},
  {id:218,cat:'metiers',fr:'Boulanger',d:'Khebbaz / Khebbaza',a:'خباز / خبازة',p:'kheb-baz',n:'La boulangerie : l-ferrane'},
  {id:219,cat:'metiers',fr:'Coiffeur / Coiffeuse',d:'7alla9 / Kwafora',a:'حلاق / كوافورة',p:'7al-la9',n:'Kwafora est un emprunt du français "coiffeuse"'},
  {id:220,cat:'metiers',fr:'Commerçant(e)',d:'Moul l7anout',a:'مول الحانوت',p:'moul l-7a-nout',n:'Litt. "le patron de la boutique"'},
  {id:221,cat:'metiers',fr:'Chauffeur de taxi',d:'Chifour dyal taksi',a:'شيفور ديال طاكسي',p:'chi-four dyal tak-si',n:'Chauffeur de bus : Chifour dyal Tobis'},
  {id:222,cat:'metiers',fr:'Mécanicien',d:'Mikanisian',a:'ميكانيسيان',p:'mi-ka-ni-sian',n:'Emprunt du français "mécanicien"'},
  {id:223,cat:'metiers',fr:'Électricien',d:'Trisiyan',a:'تريسيان',p:'tri-si-yan',n:'Emprunt du français "électricien"'},
  {id:224,cat:'metiers',fr:'Comptable',d:'Mo7asib / Mo7asiba',a:'محاسب / محاسبة',p:'mo-7a-sib',n:''},
  {id:225,cat:'metiers',fr:'Qu\'est-ce que tu fais dans la vie ?',d:'Fach ka tkhddem ?',a:'فاش كتخدم؟',p:'fach ka-tkh-dem',n:'Réponse : Ana [métier] · je suis...'},
  {id:226,cat:'metiers',fr:"J'ai trouvé un travail",d:'L9it khedma',a:'لقيت خدمة',p:'l-9it khed-ma',n:'Chercher du travail : Kanchaf 3la khedma'},
  {id:227,cat:'metiers',fr:'Je suis au chômage',d:'Ana 3aaTel',a:'أنا عاطل',p:'a-na 3a-Tel',n:'3aTla pour une femme'},
  {id:228,cat:'metiers',fr:'Combien tu gagnes ?',d:'Ch7al ka tkhallaS ?',a:'شحال كتخلص؟',p:'ch7-al ka-tkhall-aS',n:'Salaire : l-ajr · Augmentation : ziyada'},
  {id:229,cat:'metiers',fr:'Mon patron / ma patronne',d:'Moul l-khedma / la patrona',a:'مول الخدمة',p:'moul l-khed-ma',n:'Le travail en équipe : khedma f chi équipe'},
  {id:230,cat:'politesse',fr:'Je vous en prie / de rien',d:'Bla jmil',a:'بلا جميل',p:'bla jmil',n:'Réponse à chokran · très naturel'},
  {id:231,cat:'politesse',fr:'Avec plaisir / volontiers',d:'B kol mamnouniya',a:'بكل ممنونية',p:'b kol mam-nou-ni-ya',n:'Réponse polie et chaleureuse'},
  {id:232,cat:'politesse',fr:'Permettez-moi / excusez-moi',d:'Sma7 liya',a:'سماح ليا',p:'sma-7 li-ya',n:"Pour passer, interrompre, s'excuser"},
  {id:233,cat:'politesse',fr:'Après vous',d:'Tfeddel / Tfeddeli',a:'تفضل / تفضلي',p:'tfe-ddel',n:'Tfeddeli pour une femme · aussi "je vous en prie, entrez"'},
  {id:234,cat:'politesse',fr:'Permettez que je me présente',d:'Khasni n3arref b rassi',a:'خاصني نعرف براسي',p:'kha-sni n3ar-ref b ra-ssi',n:'Introduction formelle'},
  {id:235,cat:'politesse',fr:"C'est très aimable de votre part",d:'Nta mezyan bzzaf',a:'نتا مزيان بزاف',p:'nta mez-yan bz-zaf',n:'Nti mezyana pour une femme'},
  {id:236,cat:'politesse',fr:'Je ne voudrais pas vous déranger',d:'Ma bghitch n3awqek',a:'ما بغيتش نعوقك',p:'ma bghi-tch n3aw-qek',n:''},
  {id:237,cat:'politesse',fr:'Prenez votre temps',d:'Dir rasek / Ma tkhddemch f ras lik',a:'دير راسك',p:'dir ra-sek',n:'Litt. "fais-toi" = prends ton temps'},
  {id:238,cat:'politesse',fr:"C'est trop gentil",d:'Hadi mezyana bzzaf',a:'هادي مزيانة بزاف',p:'ha-di mez-ya-na bz-zaf',n:''},
  {id:239,cat:'politesse',fr:'Je vous souhaite une bonne journée',d:'Allah y3tik nharak sa3id',a:'الله يعطيك نهارك سعيد',p:'al-lah y3-tik nha-rak sa-3id',n:'Formule polie et bénissante'},
  {id:240,cat:'politesse',fr:'Puis-je vous poser une question ?',d:'Wach ymken nsewlek ?',a:'واش يمكن نسولك؟',p:'wach ymken nsew-lek',n:"Très poli avant d'interroger quelqu'un"},
  {id:241,cat:'politesse',fr:'Je vous remercie du fond du cœur',d:'Chokran bzzaf men qlbi',a:'شكرا بزاف من قلبي',p:'cho-kran bz-zaf men qlbi',n:'Expression de gratitude sincère'},
  {id:242,cat:'politesse',fr:'Vous êtes trop aimable',d:'Nta krim bzzaf',a:'نتا كريم بزاف',p:'nta krim bz-zaf',n:'Nti krima pour une femme'},
  {id:243,cat:'politesse',fr:'Bonne continuation',d:'Allah y3awnek',a:'الله يعاونك',p:'al-lah y3aw-nek',n:'Litt. "que Dieu t\'aide" · clôture chaleureuse'},
  {id:244,cat:'politesse',fr:'Je vous en suis très reconnaissant(e)',d:'Ana mamnoun bzzaf',a:'أنا ممنون بزاف',p:'a-na mam-noun bz-zaf',n:'Mamnouniya pour une femme'},
  {id:245,cat:'pronoms',fr:'Je / Moi',d:'Ana',a:'أنا',p:'a-na',n:'Le "je" marocain · très utilisé pour insister'},
  {id:246,cat:'pronoms',fr:'Tu / Toi (masc.)',d:'Nta',a:'نتا',p:'nta',n:''},
  {id:247,cat:'pronoms',fr:'Tu / Toi (fém.)',d:'Nti',a:'نتي',p:'nti',n:''},
  {id:248,cat:'pronoms',fr:'Il / Lui',d:'Huwa',a:'هو',p:'hu-wa',n:''},
  {id:249,cat:'pronoms',fr:'Elle',d:'Hiya',a:'هي',p:'hi-ya',n:''},
  {id:250,cat:'pronoms',fr:'Nous',d:'7na',a:'حنا',p:'7na',n:''},
  {id:251,cat:'pronoms',fr:'Vous',d:'Ntuma',a:'نتوما',p:'ntou-ma',n:'Pluriel de nta/nti'},
  {id:252,cat:'pronoms',fr:'Ils / Elles',d:'Huma',a:'هوما',p:'hou-ma',n:'Pas de distinction masculin/féminin au pluriel'},
  {id:253,cat:'pronoms',fr:'Mon / Ma (possession)',d:'Diali',a:'ديالي',p:'dia-li',n:'ex : dari diali = ma maison'},
  {id:254,cat:'pronoms',fr:'Ton / Ta',d:'Diatek',a:'ديالك',p:'dia-lek',n:'ex : smiytek diatek = ton prénom'},
  {id:255,cat:'pronoms',fr:'Son / Sa (masc.)',d:'Dialu',a:'ديالو',p:'dia-lou',n:'ex : dar dialu = sa maison (à lui)'},
  {id:256,cat:'pronoms',fr:'Son / Sa (fém.)',d:'Diyalha',a:'ديالها',p:'dia-lha',n:'ex : dar diyalha = sa maison (à elle)'},
  {id:257,cat:'pronoms',fr:'Notre',d:'Dialina',a:'ديالنا',p:'dia-li-na',n:''},
  {id:258,cat:'pronoms',fr:'Votre',d:'Diyalkoum',a:'ديالكم',p:'dia-l-koum',n:''},
  {id:259,cat:'pronoms',fr:'Leur',d:'Diyalhum',a:'ديالهم',p:'dia-l-hum',n:''},
  {id:260,cat:'pronoms',fr:'Celui-ci / Celui-là (masc.)',d:'Hada / Hadak',a:'هادا / هاداك',p:'ha-da / ha-dak',n:'Hada = proche · Hadak = loin'},
  {id:261,cat:'pronoms',fr:'Celle-ci / Celle-là (fém.)',d:'Hadi / Hadik',a:'هادي / هاديك',p:'ha-di / ha-dik',n:''},
  {id:262,cat:'pronoms',fr:'Ceux-ci / Ceux-là',d:'Hadu / Haduk',a:'هادو / هادوك',p:'ha-dou / ha-douk',n:'Pluriel neutre'},
  {id:263,cat:'pronoms',fr:'Qui ?',d:'Chkoun ?',a:'شكون؟',p:'chk-oun',n:'ex : Chkoun nta ? = Qui es-tu ?'},
  {id:264,cat:'pronoms',fr:"Quoi ? / Qu'est-ce que ?",d:'Ach / Achno ?',a:'أش / أشنو؟',p:'ach / ach-no',n:"ex : Achno bghiti ? = Qu'est-ce que tu veux ?"},
  {id:265,cat:'pronoms',fr:'Où ?',d:'Fin / Fain ?',a:'فين؟',p:'fin / fain',n:'ex : Fin ghadi ? = Où tu vas ?'},
  {id:266,cat:'pronoms',fr:'Quand ?',d:'Imta ?',a:'إمتى؟',p:'im-ta',n:'ex : Imta jiti ? = Quand tu es arrivé ?'},
  {id:267,cat:'pronoms',fr:'Comment ?',d:'Kifach ?',a:'كيفاش؟',p:'ki-fach',n:'ex : Kifach darti ? = Comment tu as fait ?'},
  {id:268,cat:'pronoms',fr:'Pourquoi ?',d:'3lach ?',a:'علاش؟',p:'3-lach',n:"ex : 3lach ma jitich ? = Pourquoi tu n'es pas venu ?"},
  {id:269,cat:'pronoms',fr:'Combien ?',d:'Ch7al ?',a:'شحال؟',p:'ch7-al',n:'ex : Ch7al hada ? = Combien ça coûte ?'},
  {id:270,cat:'pronoms',fr:'Lequel / Laquelle ?',d:'Anhou / Anhiya ?',a:'أنهو / أنهي؟',p:'an-hou / an-hi',n:'ex : Anhou ktab ? = Lequel des livres ?'},
  {id:271,cat:'conjonctions',fr:'Mais',d:'Walakin / Lakin',a:'ولاكن / لاكن',p:'wa-la-kin / la-kin',n:'ex : Kanbghi nji walakin ma 3andich wa9t'},
  {id:272,cat:'conjonctions',fr:'Ou (choix)',d:'Wella',a:'ولا',p:'wel-la',n:'ex : Atay wella qhwa ? = Thé ou café ?'},
  {id:273,cat:'conjonctions',fr:'Et',d:'Ou / W',a:'و',p:'ou / w',n:'ex : Ana ou nta = toi et moi'},
  {id:274,cat:'conjonctions',fr:'Donc / Alors',d:'Idhan / F had l7al',a:'إذن',p:'i-dhan',n:'ex : Idhan ghadi nmchi = Donc je vais y aller'},
  {id:275,cat:'conjonctions',fr:'Car / Parce que',d:'7it',a:'حيت',p:'7it',n:"ex : Ma jitch 7it kont 3iyan = Je ne suis pas venu car j'étais fatigué"},
  {id:276,cat:'conjonctions',fr:'Ni … ni',d:'La … la',a:'لا ... لا',p:'la ... la',n:'ex : La ana la nta = ni moi ni toi'},
  {id:277,cat:'conjonctions',fr:'Si (condition)',d:'Ila / Kun',a:'إلا / كون',p:'i-la / koun',n:'ex : Ila jiti, nkoun farhane = si tu viens, je serai content'},
  {id:278,cat:'conjonctions',fr:'Quand (temporel)',d:'Mnin / Mlli',a:'منين / ملي',p:'mnin / mli',n:'ex : Mnin wsselt, 3iyyet liya = quand tu arrives, appelle-moi'},
  {id:279,cat:'conjonctions',fr:'Bien que / Même si',d:'7tta ila',a:'حتى إلا',p:'7tta i-la',n:'ex : 7tta ila bghiti = même si tu veux'},
  {id:280,cat:'conjonctions',fr:'Ensuite / Puis',d:'Men b3d',a:'من بعد',p:'men b3d',n:"ex : Klit, men b3d nst = j'ai mangé, puis j'ai dormi"},
  {id:281,cat:'conjonctions',fr:"D'abord / Premièrement",d:'Awwalan',a:'أولاً',p:'aw-wa-lan',n:"ex : Awwalan selli, men b3d kol = d'abord prie, puis mange"},
  {id:282,cat:'conjonctions',fr:'Aussi / Également',d:'7ta / Kima',a:'حتى / كيما',p:'7ta / ki-ma',n:'ex : 7ta ana = moi aussi'},
  {id:283,cat:'conjonctions',fr:'Pourtant / Cependant',d:'M3a haka',a:'مع هاكا',p:'m3a ha-ka',n:'ex : M3a haka, bqit saber = pourtant, je suis resté patient'},
  {id:284,cat:'conjonctions',fr:'Sauf / Excepté',d:'Ghir / Ma3da',a:'غير / ماعدا',p:'ghir / ma3-da',n:'ex : Kolu jiw, ghir huwa = ils sont tous venus, sauf lui'},
];
